<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AIPL9262LT06088" failures="1" tests="12" name="tests.AccountSetup" time="93.800" errors="0" timestamp="2024-12-19T13:23:14 IST" skipped="10">
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.746">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.552">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.800">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.666">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.576">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="7.122">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.567">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.631">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="6.271">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.AccountSetup.searchBus4(FirstTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="11.739">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus4" time="8.243">
    <skipped/>
  </testcase> <!-- searchBus4 -->
  <testcase classname="tests.AccountSetup" name="searchBus" time="13.887"/>
</testsuite> <!-- tests.AccountSetup -->
